### ISSUE TITLE
前端请求接口token error问题

### ISSUE THREAD

**Issue by goodmornight** [DvcLAB/PsiAI-fe#5]
问题：前端可以获取keycloak传来的用户信息，但在请求后端接口信息时出现token error问题。

期望：前后端正常请求，无token错误问题。

**Comment by goodmornight** [comment]
## 排查问题

失败：

1. 前端修改为之前沣东服务器前端代码配置，仍**存在问题**
2. 修改auth.dvclab.com的keycloak后台使用的client配置改为与沣东keycloak后台使用client配置一致，仍**存在问题**
3. 使用第三方登录keycloak，都**无法正常请求接口**

成功：

1. 将前端换成沣东的keycloak地址和接口，可以**正确**请求接口获取数据
2. 使用李佳在keycloak创建的test1账户，通过账号密码登录，**可以正常请求接口获得数据**

## 临时解决方案

1. 使用test1账户，通过账号密码登录进行前后端接口测试

**Comment by JJLAAA** [comment]
`avatar_url`字段长度不够，先更新长度为256

**Comment by goodmornight** [comment]
## 问题

又再次出现`Token error`问题

## 问题分析
因用户信息少了一个字段`enabled`

## 期望

keycloak配置用户第三方登录后可以自动添加该字段`enabled` @linstein

**Comment by linstein** [comment]
修改login-update-profile.ftl文件，在内部添加一个不显示的user attribute输入栏，值默认为true
